---
title: "02_mapmaking"
author: "Brenna Kelly"
date: "2024-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Set-up

```{r}

library(tmap)
library(dplyr)

```

The goal of this lab is to make simple (but effective) maps using the `tmap` package.

### What is an effective map?  

Like any figure, a map should communicate a clear message as an honest representation of the data.

```{r}

plot(uk$geometry)
plot(pubs$geometry, col = alpha("goldenrod", 0.1), add = TRUE)

pubs_uk <- st_join(pubs, uk, join = st_intersects)

pubs_uk_agg <- pubs_uk |> 
  count(LAD24NM) |>
  rename(pub_count = n)
pubs_uk_poly <- merge(uk, st_drop_geometry(pubs_uk_agg), by = "LAD24NM")

tm_shape(pubs_uk_poly) +
  tm_polygons(col = "pub_count", style = "cont", palette = "viridis", 
              border.col = "white", lwd = 0.25, title = "Pub Count") +
  tm_layout(legend.position = c(0.7, 0.8), frame = FALSE)

pubs_uk_poly$land_area <- st_area(pubs_uk_poly)

pubs_uk_poly$pubs_per_10sqkm <- pubs_uk_poly$pub_count / (pubs_uk_poly$land_area / 10000)

pubs_uk_poly[which(pubs_uk_poly$pubs_per_10sqkm == max(pubs_uk_poly$pubs_per_10sqkm)), ]

tm_shape(pubs_uk_poly) +
  tm_polygons(col = "pubs_per_10sqkm", style = "cont", palette = "viridis", lwd = 0) +
  tm_layout(legend.position = c(0.7, 0.8), frame = FALSE)

tm_shape(pubs_uk_poly) +
  tm_polygons(col = "pubs_per_10sqkm", style = "quantile", palette = "viridis", lwd = 0) +
  tm_layout(legend.position = c(0.7, 0.8), frame = FALSE)

tm_shape(pubs_uk_poly) +
  tm_polygons(col = "pubs_per_10sqkm", style = "log10", palette = "-viridis", lwd = 0) +
  tm_layout(legend.position = c(0.7, 0.8), frame = FALSE)

hist(pubs_uk_poly$pub_count)

# com <- st_read("/Users/brenna/Downloads/comarea/ComArea_ACS14_f.shp")
# com_pt <- st_centroid(com)


## geographic mapping with tmap

uk <- st_read("data/uk_pubs/uk.shp")
pubs <- st_read("data/uk_pubs/pubs.shp")

tm_shape(uk) +
  tm_polygons(col = "white", border.col = "black") +
  tm_shape(pubs) +
  tm_dots(col = "gold", alpha = 0.1)

pubs$inn <- as.factor(pubs$inn)

tm_shape(uk) +
  tm_polygons(col = "white", border.col = "black") +
  tm_shape(pubs) +
  tm_dots(col = "region", alpha = 0.25)

```

### the choropleth map

```{r}

# choropleth with cancer data
com <- st_read("/Users/brenna/Downloads/comarea/ComArea_ACS14_f.shp")

# class intervals:
# https://www.rdocumentation.org/packages/classInt/versions/0.1-7/topics/classIntervals

summary(com$BrstCancr)
ggplot(com, aes(x = BrstCancr)) +
  geom_histogram()

# calculate quantiles
quantiles <- quantile(com$BrstCancr, probs = c(0, 0.2, 0.4, 0.6, 0.8, 1))

# Assign each observations to a quantile range
com$bc_quantile <- cut(com$BrstCancr, breaks = quantiles, 
                       labels = c("0-0.2", "0.2-0.4", "0.4-0.6",
                                  "0.6-0.8", "0.8-1.0"),
                       include.lowest = TRUE)

# what the distribution looks like
ggplot(com, aes(x = BrstCancr, fill = teen_birth_quantile)) +
  geom_histogram() +
  scale_fill_viridis_d() +
  xlab("Teen birth rate, per 1000 women aged 15-19") +
  ylab("Count")

```

```{r}

# default
tm_shape(com) +
  tm_polygons(col = "BrstCancr",
              palette = "viridis", lwd = 0) +
  tm_layout(title.position = c(0.05, 0.6))

# other options:
# sd, equal, quantile, kmeans, hclust, bclust, fisher, log10, cont

# all options
int_pretty <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "pretty",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "pretty", title.position = c(0.05, 0.6))

int_sd <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "sd",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "sd", title.position = c(0.05, 0.6))

int_equal <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "equal",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "equal", title.position = c(0.05, 0.6))

int_quantile <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "quantile",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "quantile", title.position = c(0.05, 0.6))

int_kmeans <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "kmeans",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "kmeans", title.position = c(0.05, 0.6))

int_hclust <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "hclust",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "hclust", title.position = c(0.05, 0.6))

int_bclust <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "bclust",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "bclust", title.position = c(0.05, 0.6))

int_fisher <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "fisher",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "fisher", title.position = c(0.05, 0.6))

int_log10 <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "log10",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "log10", title.position = c(0.05, 0.6))

int_cont <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont",  
              palette = "viridis", lwd = 0) +
  tm_layout(title = "cont", title.position = c(0.05, 0.6))

tmap_arrange(int_pretty, int_sd, int_equal, 
             int_quantile, int_kmeans, int_hclust,
             int_fisher, int_bclust, #int_log10, 
             int_cont, ncol = 3)
```

```{r}

# BORDERS

## Using `tmap`, create four maps of the variable `TeenBirth` in the `com` dataset. Use `palette = "viridis"` and the `style` (class interval) of your choice.
## - map 1: call this `border_default`
## - map 2: call this `border_black` add the argument `border.col = "black"`
## - map 3: call this `border_white` add the argument `border.col = "white"`
## - map 4: call this `border_none` add the argument `lwd = 0`
## compare all four maps using tmap_arrange()

border_default <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", 
              palette = "viridis")

border_black <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", 
              palette = "viridis", border.col = "black")

border_white <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", 
              palette = "viridis", border.col = "white")

border_none <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", 
              palette = "viridis", lwd = 0)

tmap_arrange(border_default, border_black, 
             border_white, border_none, ncol = 2)
```

```{r}
# MACH BANDS

# grayscale
lwd_wide <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont", lwd = 2,
              palette = "Greys", border.col = "white")

lwd_default <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont",
              palette = "Greys", border.col = "white")

lwd_none <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont",
              palette = "Greys", lwd = 0)

tmap_arrange(lwd_wide, lwd_default, lwd_none, ncol = 3)

```


```{r}
# viridis
lwd_wide <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont", lwd = 2,
              palette = "viridis", border.col = "white")

lwd_default <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont",
              palette = "viridis", border.col = "white")

lwd_none <- tm_shape(com) +
  tm_polygons(col = "TeenBirth", style = "cont",
              palette = "viridis", lwd = 0)

tmap_arrange(lwd_wide, lwd_default, lwd_none, ncol = 3)
```


