---
title: "03_spatial regression"
author: "Brenna Kelly"
date: "2024-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tmap)
library(spdep)

```



```{r warning = FALSE}
## begin by exploring the data
scot <- st_read("data/scotlip/scotlip.shp")

scot$cancer_SIR <- 100000 * scot$CANCER / scot$POP

# check distribution of outcome
hist(scot$cancer_SIR)

# look at counts
tm_shape(scot) +
  tm_polygons(col = "CANCER", style = "cont", palette = "-plasma", 
              lwd = 0.2, border.col = "white")

# check for spatial structure in outcome
Y <- tm_shape(scot) +
  tm_polygons(col = "cancer_SIR", style = "cont", palette = "-plasma", 
              lwd = 0.2, border.col = "white")

# check for spatial structure in outcome
X <- tm_shape(scot) +
  tm_polygons(col = "AFF", style = "cont", palette = "-plasma", 
              lwd = 0.2, border.col = "white")

tmap_arrange(Y, X) # add warning = FALSE

```



# Moran's I

```{r}

scot <- st_read("/Users/brenna/Downloads/scotlip/scotlip.shp")

scot_nb <- load("data/scot_nb.RData")
scot_listw = nb2listw(scot_nb)

moran.test(scot$cancer_SIR, 
           listw = scot_listw, 
           alternative = "two.sided", 
           randomisation = TRUE)


moran.mc(scot$cancer_SIR, 
         listw = scot_listw, 
         nsim = 999, 
         alternative = 'greater')


```


