---
title: "14_multilevel spatial models solutions"
author: "Brenna Kelly"
date: "2024-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(nlme)

```

Set up (carrying on from `03b_spatial regression.Rmd`):

```{r}

com <- st_read("data/comarea/ComArea_ACS14_f.shp")

com$poverty_scaled <- com$Pov200P / 10

# spatial structure
nb <- poly2nb(com)
com_nb_listw <- nb2listw(nb)

```


```{r}



com$dummy <- 1

com_lme1 = lme(PretBrth ~ poverty_scaled, 
               random = ~1 | dummy, 
               data = com, 
               method = "ML")

summary(com_lme1)

moran.test(residuals(com_lme1), com_nb_listw)

```



```{r}

coords <- st_coordinates(st_centroid(com))
com$X <- coords[, "X"]
com$Y <- coords[, "Y"]

vgram <- Variogram(com_lme1, 
                   form = ~ Y + X, 
                   data = com)

plot(vgram)

```

Can specify distance:

```{r}

vgram <- Variogram(com_lme1, 
                   form = ~ Y + X, 
                   data = com, 
                   maxDist = 0.5)

plot(vgram)

```

Incorporate a variogram model into the original model:

```{r}

com_lme2 = lme(PretBrth ~ poverty_scaled, 
               random = ~1 | dummy, 
               data = com, 
               method = "ML",
               corr = corSpatial(c(0.5, 0.3), 
                                  type = "spherical",
                                  form = ~ Y + X, 
                                  nugget = TRUE))

summary(com_lme2)

```

Compare the models:

```{r}

AIC(com_lme1, com_lme2)

```

Plot the residuals of `com_lme2`:

```{r}

com$res_h <- residuals(com_lme2)

tm_shape(com) +
  tm_polygons(col = "res_h", palette = "Spectral", style = "cont", lwd = 0)

```

```{r}

moran.test(residuals(com_lme2), com_nb_listw)

```

```{r}

com$res_h <- residuals(com_lme2, type = "normalized")

tm_shape(com) +
  tm_polygons(col = "res_h", palette = "Spectral", style = "cont", lwd = 0)

```


```{r}

moran.test(residuals(com_lme2, type = "normalized"), com_nb_listw)

```


