project:
  type: website
  output-dir: docs

website:
  title: "Geographical Analysis & Visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home

        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



